--Criação da tabela de pessoas
CREATE TABLE TB_CONTAS (
    id bigint generated by default as identity,
    ativa boolean not null,
    descricao varchar(255) not null,
    telefone varchar(255),
    user_id bigint,
    primary key (id)
);

CREATE TABLE TB_OPCOES (
   id bigint generated by default as identity,
   descricao varchar(255),
   image varchar(255),
   questao_id bigint,
   primary key (id)
);

CREATE TABLE TB_QUESTIONARIOS (
   id bigint generated by default as identity,
   autorizacao varchar(255),
   cliente varchar(255),
   criado_em timestamp,
   municipio varchar(255),
   conta_id bigint,
   primary key (id)
);

CREATE TABLE TB_QUESTOES (
   id bigint generated by default as identity,
   descricao varchar(255),
   questionario_id bigint,
   primary key (id)
);

CREATE TABLE TB_CONTATOS (
    id bigint generated by default as identity,
    numero varchar(255),
    nome varchar(255),
    primary key (id)
);

CREATE TABLE TB_FORMALIOS_RESPONDIDOS (
    id bigint generated by default as identity,
    chat_id varchar(255),
    formulario_id bigint,
    respondido boolean,
    primary key (id)
);

CREATE TABLE TB_QUESTOES_RESPONDIDAS(
    id bigint generated by default as identity,
    formulario_id bigint,
    opcao_id bigint,
    questao_id bigint,
    primary key (id)
);

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE TB_ROLES(
    role_id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    role_name VARCHAR(20) NOT NULL
);


CREATE TABLE TB_USERS(
    id bigint generated by default as identity,
    email varchar(255),
    password varchar(255),
    telefone varchar(255),
    username varchar(255),
    primary key (id)
);

CREATE TABLE TB_USERS_ROLES(
    user_id bigint not null,
    role_id UUID not null,
    primary key (user_id, role_id)
);

CREATE TABLE TB_USUARIOS(
    usuario_id bigint generated by default as identity,
    email varchar(255),
    nome varchar(255),
    telefone varchar(255),
    user_id bigint,
    primary key (usuario_id)
);

