--Alteração das tabelas
ALTER TABLE TB_CONTAS ADD CONSTRAINT UK_DESCRICAO UNIQUE (DESCRICAO);
ALTER TABLE TB_CONTAS ADD CONSTRAINT FK_CONTAS_USER_ID FOREIGN KEY (USER_ID) REFERENCES TB_USERS(id);

ALTER TABLE TB_OPCOES ADD CONSTRAINT FK_OPCOES_QUESTAO_ID FOREIGN KEY (questao_id) REFERENCES TB_QUESTOES(id);

ALTER TABLE TB_QUESTIONARIOS ADD CONSTRAINT FK_QUESTIONARIOS_CONTA_ID FOREIGN KEY (conta_id) REFERENCES TB_CONTAS(id);

ALTER TABLE TB_QUESTOES ADD CONSTRAINT FK_TB_QUESTIONARIO_ID FOREIGN KEY (questionario_id) REFERENCES TB_QUESTIONARIOS(id);

ALTER TABLE TB_ROLES ADD CONSTRAINT UK_ROLE_NAME UNIQUE (role_name);

ALTER TABLE TB_USERS_ROLES ADD CONSTRAINT FK_ROLES_USERS_USER_ID FOREIGN KEY (user_id) REFERENCES TB_USERS(id);
ALTER TABLE TB_USERS_ROLES ADD CONSTRAINT FK_ROLES_USERS_ROLE_ID FOREIGN KEY (role_id) REFERENCES TB_ROLES(role_id);

ALTER TABLE TB_USUARIOS ADD CONSTRAINT FK_USUARIOS_USER_ID FOREIGN KEY(user_id) REFERENCES TB_USERS(id);
